function in = CleanHeader2(in)

% function in = CleanHeader2(in) is a function that removes or sets to
% NIL potentially sensitive fields from an input structure
%
% INPUT:
% in:   structure generated by dicominfo, eg in = dicominfo(FILE.IMA)
% OUTPUT:
% in:   input structure with sensitive fields removed or set to []
%
% This field needs adjustement, probably removes too much info

% SPDX-License-Identifier: AGPL-3.0-or-later
%
% Copyright (C) 2021, Sophie G Shermer, Swansea University

in.InstitutionAddress      = '';
in.ReferringPhysicianName  = '';
in.PerformingPhysicianName = '';
in.OperatorName            = 'LW/CJ';
in.PatientName             = '';
in.PatientID               = '';
in.PatientBirthDate        = '';
in.PatientSex              = '';
in.PatientAge              = '';
in.PatientSize             = '';
in.PatientWeight           = '';
%in.BodyPartExamined       = '';
in.ImageComments           = '';
in.RequestedProcedureDescription   = '';
in.PerformedProcedureStepStartDate = '';
in.PerformedProcedureStepStartTime = '';
in.PerformedProcedureStepID        = '';
in.PerformedProcedureStepDescription = '';
in.CommentsOnPerformedProcedureStep = '';
in.InstanceCreationDate = '';
in.InstanceCreationTime = '';
in.StudyDate  = '';
in.SeriesDate = '';
in.StudyTime  = '';
in.SeriesTime = '';
in.PatientPosition   = '';
in.StudyInstanceUID  = '';
in.SeriesInstanceUID = '';
in.SOPClassUID = '';
in.StudyDescription = '';
in.SeriesDescription = '';
in.ProtocolName = 'svs_edit';
in.StudyID = '';
in.AcquisitionNumber = '';
