name: Mirror Qyber Wiki

on:
  schedule:
    - cron: '45 6 20 * *'
  push:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: mirror
      run: ./.github/mirror.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
